version: '3'
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb-alf"
    ports:
      - "27017:27017"
    command: --smallfiles
  solr:
    image: bitnami/solr:latest
    container_name: "solr"
    ports:
      - "8983:8983"
  app:
    image: alf
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    links:
      - mongodb
      - solr